language: scala
scala:
   - 2.10.6
   - 2.11.11
   - 2.12.2

jdk:
  - oraclejdk8

script:
  - sbt test
  - sbt "bench/run 3 3 2 10"
  - sbt "bench/run 30 10 5 10"
  - sbt "bench/run 50 20 10 100"

os:
  - linux
  - osx
